// src/config/status.config.js

// Columns in the status table
export const STATUS_FIELDS = [
  { key: "concept", label: "Concept" },
  { key: "framework", label: "Framework" },
  { key: "firstImplementation", label: "First implementation" },
  { key: "reachable", label: "Reachable" },
  { key: "differentLanguages", label: "Different Languages" },
  { key: "mobileReady", label: "Mobile ready"},
  { key: "secondRunContent", label: "Second run Content" },
  { key: "secondRunDesign", label: "Second run Design" },
  { key: "accepted", label: "Accepted" },
];

// Per-page status
export const PAGES_STATUS = [
  {
    id: "home",
    label: "Home",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "More content, not usable on mobile at the moment",
  },
  {
    id: "company",
    label: "Company",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Auto-generated first version – review copy & placeholder images",
  },
  {
    id: "company/flexibility",
    label: "Company/Flexibility",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Auto-generated first version – review copy & placeholder images",
  },
  {
    id: "company/specializations",
    label: "Company/Specialisation",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Auto-generated first version – review copy & placeholder images",
  },
  {
    id: "company/internationality",
    label: "Company/Internationality",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Auto-generated first version – review copy & placeholder images",
  },
  {
    id: "company/automatisation",
    label: "Company/Automatisation",
    concept: false,
    framework: false,
    firstImplementation: false,
    mobileReady: false,
    reachable: false,
    differentLanguages: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "automobile",
    label: "Automobile",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Auto-generated first version – review copy & placeholder images",
  },
  {
    id: "automobile/performance",
    label: "Automobile/Performance",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Auto-generated first version – review copy & placeholder images",
  },
  {
    id: "automobile/customers",
    label: "Automobile/Customers",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Auto-generated first version – review copy & placeholder images",
  },
  {
    id: "automobile/methods",
    label: "Automobile/Methods",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Auto-generated first version – review copy & placeholder images",
  },
  {
    id: "automobile/car-clinics",
    label: "Automobile/Car Clinics",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Auto-generated first version – review copy & placeholder images",
  },
  {
    id: "customer-satisfaction",
    label: "Customer Satisfaction",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "finanzmarket",
    label: "Financial Market",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "finanzmarket/online-surveys",
    label: "Financial Market/Online Surveys",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Auto-generated first version – review copy & placeholder images",
  },
  {
    id: "finanzmarket/reporting-system",
    label: "Financial Market/Reporting System",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Auto-generated first version – review copy & placeholder images",
  },
  {
    id: "team",
    label: "Team",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Tags to close to each other on mobile view. Jump to top button.",
  },
  {
    id: "solutions",
    label: "Solutions",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "contact",
    label: "Contact",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Contact form with no functionality so far.",
  },
  {
    id: "imprint",
    label: "Imprint",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Maybe include Logo somewhere. Not sure if to much doubled informations.",
  },
  {
    id: "data-protection",
    label: "Data Protection",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Has to be updatet with new website requirements (especially contact form and Google).",
  },
  {
    id: "directions",
    label: "Directions",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "job-career",
    label: "Jobs & Carrer",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Jobs offers would work.",
  },
  {
    id: "menue-framework",
    label: "Menue Framework",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: false,
    differentLanguages: true,
    mobileReady: true,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Add Chinese. Better sidebar(Colors) and also better Languge change inclusion.",
  },
  {
    id: "status",
    label: "Status",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: true,
    secondRunDesign: true,
    accepted: true,
    todos: "Update content. Nice table if I got time.",
  },
  {
    id: "general",
    label: "General",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: false,
    differentLanguages: true,
    mobileReady: true,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: " ",
  },
];

// Release notes – arbitrary length, arbitrary items per note
export const RELEASE_NOTES = [
  {
    id: "2025-12-05-implementation-footer-pages",
    version: "1.1.0",
    title: "Implementation of all footer pages",
    date: "2025-12-02",
    description:
      "Implemented all footer-related pages with initial content drafts, applied the first round of design refinements, and introduced the status page.",
    items: [
      "Initial implementation of the 'Contact' page",
      "Initial implementation of the 'Imprint' page",
      "Initial implementation of the 'Directions' page",
      "Initial implementation of the 'Data Protection' page",
      "Added status overview page",
      "Adjusted all menu icons to better match their labels and content",
      "Introduced ParallaxClouds for a more dynamic background experience",
      "Added a framework for embedding Google Maps and Google Street View content",
      "Fixed page switching state issues",
      "Added support for an additional language: Chinese"
    ],
  },
  {
    id: "2025-12-02-first-implementation",
    version: "1.0.0",
    title: "Initial implementation for demo purposes",
    date: "2025-12-02",
    description:
      "Set up the project structure, made the first design decisions, and implemented the base framework and home page for internal demonstrations.",
    items: [
      "Added page wrappers for a consistent experience across all pages",
      "Defined design choices and created page overviews for planned content",
      "Implemented desktop and mobile navigation menus",
      "Integrated i18n for language switching",
      "Defined color palettes for dark and light mode",
      "Deployed the initial version of the website"
    ],
  },
];
