// src/config/status.config.js

// Columns in the status table
export const STATUS_FIELDS = [
  { key: "concept", label: "Concept" },
  { key: "framework", label: "Framework" },
  { key: "firstImplementation", label: "First implementation" },
  { key: "reachable", label: "Reachable" },
  { key: "differentLanguages", label: "Different Languages" },
  { key: "mobileReady", label: "Mobile ready"},
  { key: "secondRunContent", label: "Second run Content" },
  { key: "secondRunDesign", label: "Second run Design" },
  { key: "accepted", label: "Accepted" },
];

// Per-page status
export const PAGES_STATUS = [
  {
    id: "home",
    label: "Home",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "More content, not usable on mobile at the moment",
  },
  {
    id: "company",
    label: "Company",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "company/flexibility",
    label: "Company/Flexibility",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "company/specialisation",
    label: "Company/Specialisation",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "company/internationality",
    label: "Company/Internationality",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "company/automatisation",
    label: "Company/Automatisation",
    concept: false,
    framework: false,
    firstImplementation: false,
    mobileReady: false,
    reachable: false,
    differentLanguages: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "automobile",
    label: "Automobile",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "automobile/performance",
    label: "Automobile/Performance",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "automobile/customers",
    label: "Automobile/Customers",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "automobile/methods",
    label: "Automobile/Methods",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "automobile/car-clinics",
    label: "Automobile/Car Clinics",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "customer-satisfaction",
    label: "Customer Satisfaction",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "financial-market",
    label: "Financial Market",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "financial-market/online-surveys",
    label: "Financial Market/Online Surveys",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "financial-market/reporting-system",
    label: "Financial Market/Reporting System",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "team",
    label: "Team",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "solutions",
    label: "Solutions",
    concept: false,
    framework: false,
    firstImplementation: false,
    reachable: false,
    differentLanguages: false,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "contact",
    label: "Contact",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Contact form with no functionality so far.",
  },
  {
    id: "imprint",
    label: "Imprint",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Maybe include Logo somewhere. Not sure if to much doubled informations.",
  },
  {
    id: "data-protection",
    label: "Data Protection",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Has to be updatet with new website requirements (especially contact form and Google).",
  },
  {
    id: "directions",
    label: "Directions",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "",
  },
  {
    id: "jobs&career",
    label: "Jobs & Carrer",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Jobs offers would work.",
  },
  {
    id: "menue-framework",
    label: "Menue Framework",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: false,
    differentLanguages: true,
    mobileReady: true,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: "Add Chinese. Better sidebar(Colors) and also better Languge change inclusion.",
  },
  {
    id: "status",
    label: "Status",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: true,
    differentLanguages: true,
    mobileReady: false,
    secondRunContent: true,
    secondRunDesign: true,
    accepted: true,
    todos: "Update content. Nice table if I got time.",
  },
  {
    id: "general",
    label: "General",
    concept: true,
    framework: true,
    firstImplementation: true,
    reachable: false,
    differentLanguages: true,
    mobileReady: true,
    secondRunContent: false,
    secondRunDesign: false,
    accepted: false,
    todos: " ",
  },
];

// Release notes – arbitrary length, arbitrary items per note
export const RELEASE_NOTES = [
    {
    id: "2025-12-05-implementation-footer-pages",
    version: "1.1.0",
    title: "Implementation of all Footer pages",
    date: "2025-12-02",
    description:
      "Implementation of all Footer pages and first content drafts. Additionaly some first adjustments to so far designs. Also first registration of the status page.",
    items: [
      "First implementation of the 'Contact' page",
      "First implementation of the 'Imprint' page",
      "First implementation of the 'Directions' page",
      "First implementation of the 'Data Protection' page",
      "First implementation of the 'Contact' page",
      "Added Status page",
      "Adjustest all symbols in the menues to fitting icons to the texts",
      "Added general implementation of ParallaxClouds for nicer Backgrounds",
      "Framework for easy Google Maps and Google Street view content",
      "Fixed Page switch error",
      "Added language: Chinesse"
    ],
  },
  {
    id: "2025-12-02-first-implementation",
    version: "1.0.0",
    title: "First implementation for demo porpuses",
    date: "2025-12-02",
    description:
      "Set up the project, first design decision and implemented the framework for all pages and the Home page for internal demenstration.",
    items: [
      "Added Page wrappers for consisten Experiences on all pages",
      "Design choices and page overviews what should be included",
      "Menue view for desktop and mobile devices",
      "i-18n integration for language change",
      "color plates for dark and lightmode",
      "hosting of the website"
    ],
  },
];
